name: Java CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
    - name: build and test cadc-dali
      run: cd cadc-dali && gradle --info clean build javadoc checkstyleMain install
      
# cadc-dali-pg is not yet cleanup to pass checkstyleMain
    - name: build and test cadc-dali-pg
      run: cd cadc-dali-pg && gradle --info clean build javadoc install
      
    - name: build and test cadc-sia
      run: cd cadc-sia && gradle --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-datalink-server
      run: cd cadc-datalink-server && gradle --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-soda-server
      run: cd cadc-soda-server && gradle --info clean build javadoc checkstyleMain install

    - name: install WCSLIB (libwcs7)
      run: sudo apt-get update && sudo apt-get install -y libwcs7

    - name: build and test cadc-data-ops-fits
      run: cd cadc-data-ops-fits && gradle --info clean build javadoc checkstyleMain install
